### PR TITLE
Bylabel contain

### PR DESCRIPTION
**Pull request by pythonissam**
Before submitting your PR, check that you've:

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddocks for new, public APIs

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

ref: https://github.com/yesodweb/yesod/issues/1480

### CODE REVIEW

**Comment by MaxGabriel** [comment]
Can you also update the deprecation warnings for the old byLabel to point to byLabelContains for an exact replacement?

**Comment by MaxGabriel** [comment]
@pythonissam LGTM. Yesod-test 1.6.1 was released after you started this PR though, can you bump the version you're using in your Cabal file, `@since` docs, and Changelog?

**Comment by pythonissam** [comment]
Is this alright? Besides, travis seems to fail. Is this okay?

**Comment by MaxGabriel** [comment]
@pythonissam Yep that looks good. The Appveyor tests were failing because of a merge conflict with master. It looks like all but one of the Travis tests passed (and the failure was unrelated to your changes). I fixed two merge conflicts in your PR, and I'll let CI run on that before merging.

**Comment by pythonissam** [comment]
I see. Thank you.

**Comment by MaxGabriel** [comment]
Merged, thanks for your work here @pythonissam!

@snoyberg Can you add me as a maintainer of yesod-test on hackage? I couldn't release this

**Comment by snoyberg** [comment]
Done!

**Pull request merged**
