### PR TITLE
websockets example

### PR DESCRIPTION
**Pull request by dschalk**
I added to my branch a yesod-websockets example along with some commentary explaining the example and the general usefulness of websockets. I would be honored to see it incorporate it into the main yesodweb/yesod repository. I am open to suggestions for changes. 
I have code which computes all "impossibles" (see "Websockets_for_Browser_Control" in "Game-Example") but I thought that might be too extraneous for the yesod-websockets repository. Anyway, if you see value in my work and it is deemed appropriate for incorporation into the Yesod repository, please take it as it is, or tell me how you would like for me to proceed. -- David Schalk/schalkbox@gmail.com

### CODE REVIEW

**Comment by snoyberg** [comment]
Was this intended to be a submodule? I'm quite confused by what I'm seeing here.

The normal way to make a pull request is:

1. Fork the repository
2. Clone your fork to your local machine
3. Make commits on your local machine
4. Push back to Github
5. Make a pull request on Github

**Comment by dschalk** [comment]
I apologize for wasting your time.  I forked the Yesod repository, added the “Game-Example” subdirectory with files that compile and run on my linux box, entered “git add . “ and also “git add -A” in my terminal, entered “git commit” and wrote a comment, and then entered “git push -u origin master”. I don't know if this is normal, but the repo at dschalk/yesod/yesod-websockets does not have the Game-Example subdirectory and files, just a hollow entity called “Game-Example”. The subdirectory and files are present at dschalk/yesod-websockets-schalk, but that is not a fork of yesodweb/yesod/yesod-websockets.

I don't know why I got the message “The Travis CI build could not complete due to an error “.

**Comment by snoyberg** [comment]
That makes sense. If you do that process again, but this time *without* copying over the .git directory from inside Game-Example, it should work better.

**Comment by dschalk** [comment]
Update: I removed the Game-Example directory and pushed. Then, I put it back and pushed again. This time, the proposed addition showed up in dschalk/yesod/websockets. I think I have succeeded in making a pull request.

**Comment by dschalk** [comment]
The three files I am proposing to add are at https://github.com/dschalk/yesod/commit/b9bfb688db17b281759f7c29de9b97e2f882cc10

**Comment by creichert** [comment]
@dschalk We will be able to see the diff'ed files when you make the PR succesfully :). I briefly glanced at the files and it looks pretty good. I highly suggest you run the `hlint` executable on your code before submitting the PR, though. 

I think my biggest suggestion would be to stylistically try to stay within 80 columns as some of us have smaller screens so it's difficult to review (just my opinion). It will help get some of the low-hanging fruit out of the way so we can focus on reviewing the Game.


@snoyberg I can help review and cleanup the examples in `yesod-websockets` if this gets merged.

**Comment by dschalk** [comment]
Christopher, thanks for the hlint suggestions. I installed hlint, used it, and tidied up the files. I'm reluctant to push the branch again, having already caused too much inconvenience.

**Comment by geraldus** [comment]
Just commit your changes and they will go to this pull request.

**Comment by snoyberg** [comment]
@creichert Thank you for the offer, much appreciated! I trust merge abilities here, please feel free with it when you think it's ready. I've looked it over as well, and (1) I think the example is good, and (2) I agree with the feedback you've given so far.

**Comment by creichert** [comment]
@snoyberg awesome, thanks.

@dschalk  How can I test it?

```

$ cabal exec -- runhaskell Game-Example/score.hs 

Game-Example/score.hs:6:18:
    Could not find module ‘Conduit’
    Use -v to see a list of the files searched for.

Game-Example/score.hs:14:18:
    Could not find module ‘Fm’
    Use -v to see a list of the files searched for.

```

The example is very heavy in html and text. I think being a bit more concise in the writeup and the html/javascript (if at all possible) would help.

Quite a bit of the PR seems like auto generated html. I think if you can remove that and update your PR it will be significantly less overwhelming. See my quick patches here: https://gist.github.com/creichert/09d45804db657181005f

Look at using a gitignore file https://help.github.com/articles/ignoring-files/.

**Comment by dschalk** [comment]
I removed most of my commentary from "Websockets_for_Browser_Control.md". I think it got in the way of the explanation of how the application works.  I also deleted the some extraneous, commented-out code from Fm.hs. 
  I tested the application by opening four browser windows and playing the game. If you click score and make the number 20, you gain a point. If you perform three computations and don't end up with 20, or if the time runs out, you lose a point. If you click "IMPOSSIBLE" and wait 60 seconds you gain a point. Finally, if you click "IMPOSSIBLE" and then click "SCORE" in another browser window two outcomes are possible. Either you compute 20 within the time limit and gain a point, leaving the impossible clicker with a one point deduction; or you let 30 seconds elapse or compute something other than 20 and lose a point. If you lose a point, the clicker of "IMPOSSIBLE" gains 2 to make up for the tentative initial deduction and award a point for successfully clicking "IMPOSSIBLE".. It takes a while for the two point addition to show up on the scoreboards, which surprised me a little since other score changes are quickly displayed. 
I'll plan to push the revisions later this afternoon.

**Comment by dschalk** [comment]
I now plan to send send the revised files later this evening or tomorrow morning. 
Since my files might become become part of the repo, I want to avoid embarrassing the team by conforming at least a little better to Javascript best practices. Douglas Crockford has pronounced global variables to be evil because of the potential for name clashes. I think maintaining the scoreboard and setting timers with global variables in the game of 'Score' is not only appropriate, but is so simple and effective as to merit being called "elegant." So, I am keeping the global variables but creating a namespace to prevent collisions. "T" has become "DS_T" and the "DS_" prefix is being affixed to the other global variables as well. 
@creichert  I have thought about making the code more concise by reusing some functions, such as elephant and localCalc. But then I would need to add more variables and tests to assure proper behavior under the various contingencies. It seems more efficient to write a little extra code and call elephent, elephant1, or elephant2 depending on circumstances. The same goes for localCalc, localCalc2, and localCalc3, and the pair firstCalc and calculate. I think it is easier for the browsers to load a little bit of extra code rather than deal with a bunch of additional contingency tests over and over during game play. 
I didn't knowingly submit any auto generated html. I coded everything all by hand. 
Thanks for reminding me about small monitor screens. I'll try to keep everything in the next revision within bounds.

**Comment by creichert** [comment]
@dschalk Sounds great! Don't worry about the auto-generated code. I assumed it was an accident.

Glad to hear you are improving it! The extra code *can* be problematic as we need to make sure the example is low maintenance and continues to work for everyone who tries it as long as possible. As it stands I have a hard time understanding what's going on. It sounds like you have some ideas on how to work with that, though.

As a start, the main spots that I am having trouble with would be:

https://github.com/yesodweb/yesod/pull/902/files#diff-441bd70ef937d7342469f419e2e3e51bR67

I think you should break this down into some smaller functions that you can reuse across the various calc* functions. I think it would be nice to give them names which indicate what they do (and why they are different).

https://github.com/yesodweb/yesod/pull/902/files#diff-441bd70ef937d7342469f419e2e3e51bR67

I would use something like `concat` as oppose to `++` in this example. Same in the h* functions.


Have you considered adding some data types for the various tuples and lists being passed around? I think some data type would give this a lot more readability and probably clean up the type signatures.


Can you also include some short instructions to compile and run it? I haven't been able to run it yet.

**Comment by dschalk** [comment]
@creichert Just go into the Game_Example subdirectory and enter "runghc score". It should fire right up. You do need to install `stm-lifted` and `conduit-combinators`, as noted in the yesod/yesod-websockets README.md. I better include that information in the Game_Examples subdirectory. 
Then, open localhost:3000 in a few browser windows. To get started with something simple, click ROLL (as many times as you like) and click SCORE when you want to try to compute the number "20" in two or three stages. If you do, you'll see your score increase. To give the game a hard test, click IMPOSSIBLE in one window and SCORE in another. Different things happen depending on whether or not you make the number 20 withing thirty seconds.
It didn't occur to me to explain the Fm module. It is some old boilerplate I've had laying around for quite a while. Last Spring I was doing things such as trying to get Haskell to compute the 104 impossible dice rolls as fast a Javascript. I couldn't do it. But now that you mention it, I see how people might want to know how Fm.hs works, even though it is not relevant to the use of websockets for browser control. I will fix it up and make it more user friendly.
Just to see how the game works, you could go to score.nodejitsu.com. I've had that Node.js version online for a while. It's a beta version. Rather than run it through more tests and refinements, I turned my attention to developing a Haskell version, which is what I sent you. The node.js version is functional.
The Fm module generates random numbers and displays all solution in an HTML string. In Game_Example, "runghc Fm" runs the module in stand-alone mode. Fm.hs has nothing to do with websockets, but the game would be too barebones if players couldn't see the solutions. The Node.js version allows players to enter numbers of their own choice, rather than only accept random rolls, but I didn't encumber the yesod-websockets example with code for doing that or for adjusting game parameters.. 
I think score.hs will compile after you install `stm-lifted` and `conduit-combinators`. I added the README.md file after finding out why chat.hs wouldn't compile. I don't know what additional libraries would make Fm.hs run for you. Maybe I should make a score.cabal file so the "depends" section can assure that all the necessary libraries are present.

**Comment by creichert** [comment]
I've reviewed the code again and while I think it has come a long way, I don't think it should be merged it in it's current state.

The example is very extensive and is primarily targeted towards the Javascript WebSockets control mechanisms. I think a good example for this repository would focus on a specific part of the game relevant to using WebSockets with Yesod in a concise way. 

This example might fit better with the other larger examples in the wiki:  https://github.com/yesodweb/yesod/wiki/yesod_tutorial.

Have you considered releasing this as a standalone app on Hackage?

**Comment by dschalk** [comment]
My example is intended to show websockets facilitating something very close to peer-to-peer communication. webRTC  RTCDataChannel real time game demos are up and running in Chrome, Firefox, and Opera. When standards are solidified and there is more browser support, webRTC will be a good choice for implementing games such as Score. Until then, a fast server (such as Warp) and a robust API (such as Yesod) are needed to facilitate communication among browsers. 
I left Michael's chat.hs file intact and added Javascript code to send and parse messages that trigger various events in browsers. I used promises and bacon.js in the node.js version of Score (score.nodejitsu.com). I suspect that using bare-bones Javascript and Jquery with global variable runs faster than code with monad-like promises and bacon.js reactive functionality. Be that as it may, score.hs performs flawlessly in my test environment.
I think I understand why you want something simpler than the simplified version of the game of Score that I submitted in my pull request. However, I think it is more important to show that yesod-websockets can reliably facilitate fairly complex browser interactions, so I am reluctant to submit anything simpler than the simplified version of Score which is currently in my pull request.

**Comment by dschalk** [comment]
I enjoyed initiating cascading side effects by merely changing the values of global variables in my Javascript code, but this is probably too jarringly unorthodox for inclusion in the yesod-websockets repo. I plan to re-write the Javascript portion in a functional, reactive style using Rx or Bacon. 
Maybe FPComplete is a better place to showcase yesod-websockets as a facilitator of real time, multi-user interactivity more complex than exchanging text messages in chat rooms. I thought of offering the game of *Score* as a pull request because the Haskell part is only a slight deviation from Michael's chat example. I wanted to take chat one step further and demonstrate the potential of websockets messages as triggers for events in browsers. I still plan to do that, probably where I can show the running example. Probably at FPComplete.
Best regards,
David

**Comment by creichert** [comment]
@dschalk That sounds like a good idea. We can link to the write-up and being able to run the example would be great.

**Comment by dschalk** [comment]
Alright. By the way, my last commit turned out to be buggy. Streamlining the code by creating a re-usable function had some unanticipated side effects. I pushed a bug-free version this afternoon, so if anyone wants to examine the code they should look for the latest version and not the last version before I closed the pull request.
Thanks for your insight. Streamlining Fm.hs didn't introduce any untoward side effects; it only improved the code.
Cheers!

**Comment by dschalk** [comment]
Hey Christopher,

I got overly enthusiastic about the vast potential of websockets technology
when I saw what it could do for my Game of Score project. Compared with
Ajax calls, websockets seemed miraculous.  Anyway, I vastly improved the
half-baked app I proposed  as a yesod-websockets example, and I wrote the
beginnings of a wiki/tutorial in the README.md, all at
https://github.com/dschalk/score2 . The code is also at
https://www.fpcomplete.com/user/dschalk/score2. Now I want to deploy the
app and I am finding it difficult. It was easy to upload to OpenShift, but
I don't know why it wouldn't compile there. I wish I could deploy from FP
Complete directly to AWS, where I have opened a free account. If you would
be so kind as to share any thoughts you might have about getting the game
of Score online, I would sure appreciate it.  -- David

**Comment by creichert** [comment]
@dschalk What were the errors when compiling?

At a basic level, you want to compile the app locally (for the same architecture) and upload the binary to your hosting environment. For aws, you would simply do a `cabal build` followed by using `scp dist/build/app/app ubuntu@IPADDRESS:`. Once it's uploaded, you can run the exe directly and access it via the port configured in the config/settings.yml.

AWS should support websockets without any further configuration (that's what I use for an app). Make sure you're firewall exposes port 80, or whatever you are using.

Does that help? I'll be happy to help if you hit anymore issues.

**Comment by dschalk** [comment]
I'll give it a try. Thanks,

**Comment by dschalk** [comment]
Yo Christopher,

I think I made some progress, but I am still lost.

scp seemed to work, but I don't know how to navigate to the executable 
at AWS.

```
e@e:~$ scp -v score2/dist/build/server/server ubuntu@52.0.3.31
Executing: cp '--' 'score2/dist/build/server/server' 'ubuntu@52.0.3.31'
e@e:~$
```
I ssh'd into someplace, but my app executable wasn't there.

```
e@e:~$ ssh -i david.pem ubuntu@52.0.3.31
The authenticity of host '52.0.3.31 (52.0.3.31)' can't be established.
ECDSA key fingerprint is 
5c:8b:93:82:1c:47:a8:3c:70:d5:60:93:86:eb:84:2a.
Are you sure you want to continue connecting (yes/no)? yes
Failed to add the host to the list of known hosts 
(/home/e/.ssh/known_hosts).
Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-44-generic x86_64)

 * Documentation: https://help.ubuntu.com/

  System information as of Wed Mar 4 01:44:48 UTC 2015

  System load: 0.0 Processes: 98
  Usage of /: 16.6% of 7.74GB Users logged in: 0
  Memory usage: 10% IP address for eth0: 172.31.36.244
  Swap usage: 0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud


Last login: Wed Mar 4 01:44:48 2015 from 
c-73-168-20-133.hsd1.in.comcast.net
ubuntu@ip-172-31-36-244:~$ pwd
/home/ubuntu
ubuntu@ip-172-31-36-244:~$
ubuntu@ip-172-31-36-244:~$ ls
ubuntu@ip-172-31-36-244:~$ ls -a
. .. .bash_history .bash_logout .bashrc .cabal .cache .ghc .profile .ssh
ubuntu@ip-172-31-36-244:~$
```
sudo apt-get install ghc got me ghc-1.7.6 . I got cabal-install 1.16. 
cabal install Cabal fails for lack of sufficient memory. cabal install 
cabal-install fails because of "Missing (or bad) header file: zlib.h". 

I wonder if I ssh'd into the same place scp scp sent my binary file. I 
feel like I am making progress, but I am still lost. Your advice was 
helpful up to where I got stuck. How can I run the exe directly? Where 
is config/settings.yml?

I am very grateful for your assistance. By the way, my work-in-progress 
description of my project is published at 
http://dschalk.github.io/score2/ The appendix shows how Haskell list 
comprehension deftly computed some things that might otherwise have 
required quite a bit of complicated code.

**Comment by dschalk** [comment]
After scp, an application executable appeared in the application root directory. It is named ubuntu@52.0.3.31.  "./ubuntu@52.0.3.31" loads the app, same as "dist/build/server/server".

**Comment by dschalk** [comment]
I guess I scp'd dist/build/server/server to my application root directory with the new name of ubuntu@52.0.3.31 .  I tried ubuntu@ip-172-31-36-244, ubuntu@172-31-36-244, and some others. Invariably, they create copies of my executable in the application root directory of my Ubuntu 14.04 box here in Bloomington, Indiana. 
screenshot from 2015-03-04 02 16 35

**Comment by creichert** [comment]
@dschalk When using `scp`, make sure to put a semicolon at the end of the host you are sending it to or it will copy it to a file with that name.

`scp ./dist/build/app/app ubuntu@52.0.3.31:`

**Comment by dschalk** [comment]
I added the colon, uploaded the executable file named 'score2', ssh'd in and ran ./score2 3000. It loaded. I tried port 80 but I don't have permission for that. 

I know about the private IP address172.31.36.244 and the public one I used for ssh and scp, 52.0.3.31 .  My app is running on port 3000 somewhere but I don't know what url to put in my browser so I can see it, test it, and marvel at the wonder of it all.

**Comment by creichert** [comment]
@dschalk You need to modify the "Security Group" (see your screenshot). You need to open the firewall so you can access the app. I would first open port 3000 and test that to make sure your app is serving correctly. Then, change the port in your apps config/settings.yml.

Does that help?

**Comment by dschalk** [comment]
These screen shot show what I did in "Security Group".  I didn't see any mention of a firewall, or an option for opening port 3000. 

My app doesn't have a config directory. There is a file named ".project-settings.yml" in the root directory. I think cabal init put it there. It is shown in the third attachment. I set the port from the command line when I load the app. 

screenshot from 2015-03-04 15 01 41


screenshot from 2015-03-04 14 51 09
://cloud.githubusercontent.com/assets/2214003/6491951/bb16aaf2-c27e-11e4-9422-0e608b3010fc.png)

**Comment by dschalk** [comment]
screenshot from 2015-03-04 14 51 09

**Comment by dschalk** [comment]
screenshot from 2015-03-04 14 49 57

**Comment by dschalk** [comment]
I changed "Source" to "Anywhere 0.0.0.0/0

**Comment by dschalk** [comment]
Now I see what you mean by opening ports. ssh timed out all morning. Then I opened port 22 in addition to port 80 and got right in. I changed "Source" back to my IP address.  A screen shot is attached.

Much Googling and clicking around in circles in the AWS site, and still I have no clue about the possible need for a .yml config file. 

After accessing my AWS Ubuntu console, I restarted score2 on port 3000. I hate to keep asking questions, but I just can't figure this  out: What URL might locate my running app? Presumably it is <some IP address>:3000 but how can I find <some IP address>. 


screenshot from 2015-03-05 14 27 54

**Comment by creichert** [comment]
@dschalk 

- Have you assigned an "Elastic IP address" to this instance (see the option under "Security Groups")? This will give you a publicly accessible IP. The "Destination" IP in the screenshot is private to your AWS VPN.

- Open up port 3000 in the Security Group settings for initial testing of your app. Once that works, you will need to serve your app directly on port 80 or have a reverse proxy map port 80 -> 3000.

Set your port number here https://github.com/dschalk/score2/blob/master/Main.hs#L120. Presumably, on your AWS instance you want to use port 80 unless you are using a reverse proxy:

Does that help?

**Comment by dschalk** [comment]
The elusive URL turned out to be "Public DNS", which was right in front of me the whole time on the "Instances" page at the AWS site. I thought "DNS" stood for "Domain Name Server", and the game of Score is certainly not a name server. Oh well. The game of Score is up and running on the Internet at ec2-54-152-189-34.compute-1.amazonaws.com:3000.

The method for setting the port turned out to be a red herring. I started the project with Jasper Van der Jeugt's websockets, which has the port number hard-coded into the chat app. I changed it so I could set the port from the command line when I launch the app. The app that is running on the Internet was fired up with the command "./server 3000".  

My main goal is accomplished. Thank you for taking the time to get me oriented. My experience with web hosts before now was running PHP on a shared Apache server at Lunarpages.com. There, I have no control over the server. I am thinking about moving my Lunarpages sites to AWS. I guess I could run an Apache or nginx server in the same AWS instance that holds Score. I'll have to wait and see how limited the micro instance is. 

I have been using FP Complete with dschalk/score-haskell rather than dschalk/score2 at Github. score-haskell is a trimmed down version with no impossibles calculations and not even a README. I used the small repo to try to get something going at Redhat Openstack. The free gear seemed to compile the code fine, but a message popped up saying it was taking longer than normal and said to refresh the page in a couple of minutes. After the page refresh, I could find no evidence at all that anything had happened. I think it runs out of memory and forgets everything.  I think it would work if I paid for more resources. There is no need for that now.

Best regards,
David

**Comment by dschalk** [comment]
The address of the running app is http://ec2-52-1-237-167.compute-1.amazonaws.com:3000/

**Comment by dschalk** [comment]
Do you use a script that loads your server when your instance is refreshed or rebooted (same thing?). I start the servers from terminals, and they go down whenever the terminal processes are killed. I re-boot my computer frequently and would prefer not to have to ssh into AWS each time I reboot, and then have to keep the terminals perpetually open. 

I am glad to see that, while latency is noticeable, it isn't enough to interfere with competitive game play.

**Comment by dschalk** [comment]
Now it's running at:

http://ec2-54-152-189-34.compute-1.amazonaws.com:3000

http://ec2-52-0-9-178.compute-1.amazonaws.com:3000

**Comment by dschalk** [comment]
It's now at http://ec2-52-1-178-22.compute-1.amazonaws.com:3000/ 
I'm trying to compose a script for the User Data box at the AWS site that will load the app when the instance boots. Do you put something in User Data?

**Comment by dschalk** [comment]
*Score*, at http://ec2-54-152-4-245.compute-1.amazonaws.com:3000/ , was still running after I re-booted my home computer. I'm pretty sure it will start automatically after I stop and start my AWS EC2 instance, but I don't want to test that right now because re-starting changes the IP address. 

Here's what I did. I ssh's into my AWS Ubuntu instance and created a file I named "score.conf" in /etc/init. /etc/init/score.conf is a text file consisting of three lines:
```
start on startup
chdir /home/ubuntu
exec /home/ubuntu/server 3000
```
I started the app during an ssh session with the command 'initctl start score'. Then I disconnected, re-booted, fired up a browser and found that the game was still running at 'http://ec2-54-152-4-245.compute-1.amazonaws.com:3000/ '.

Thanks for helping me through the first steps of getting 'Score' online. I had ssh's into virtual machines when I was running from Cabal Hell, but I had no inkling that I would be doing something similar at AWS. I guess this conversation is over, but I would appreciate knowing that you saw this. So, if you are reading this, répondez s'il vous plaît.

**Comment by creichert** [comment]
@dschalk Congrats, that all looks correct to me. AWS has it's own learning curve :).

One thing to note is that I mostly compile on my local machine and push the compiled binary up to the server.

I use the Keter webserver which can help avoiding the need to ssh into the machine so much and helps with certain parts of the deployment process: https://github.com/snoyberg/keter

**Pull request closed without merging**
