### PR TITLE
Add simple authentication helpers

### PR DESCRIPTION
**Pull request by s9gf4ult**
I think it must be in `yesod-core`

### CODE REVIEW

**Comment by snoyberg** [comment]
Can you clarify why this must be in `yesod-core`? This looks like it would be a great piece of code to start in a separate library to allow the API to evolve and, once stabilized, consider moving into a more core package.

**Comment by s9gf4ult** [comment]
This is trivial implementation of common standardized methods of authentication. Many users will need this and it looks like core functionality for any web framework. But if you think it must be in separate package I will create some.

**Comment by snoyberg** [comment]
I'm not necessarily opposed, I just wanted to understand the "must" comment, which I think I get now. Here's my recommendation:

* The non-Yesod stuff could likely go into wai-extra instead to be more generally available
* I'd avoid `decodeUtf8`, since it's a partial function. I'd instead use `decodeUtf8With lenientDecode`
* Instead of putting this in a dedicated module, let's just add it to Yesod.Core.Handler

Does that sound reasonable?

**Comment by s9gf4ult** [comment]
Ok, so: 

* move `extractXAuth` to `wai-extra` 
* use `decodeUtf8With lenientDecode`
* move `lookupXAuth` to `Yesod.Core.Handler` 

looks logical for me.

**Comment by snoyberg** [comment]
Cool. Would you be able to send a PR?

**Comment by s9gf4ult** [comment]
Yes, I will prepare PR towards evening.

**Comment by s9gf4ult** [comment]
Ok, ive patched `wai-extra` here https://github.com/yesodweb/wai/pull/352

**Comment by snoyberg** [comment]
Looks good, I'm releasing both to Hackage now. Thanks!

**Pull request merged**
