### PR TITLE
Better monads

### PR DESCRIPTION
**Pull request by snoyberg**

### CODE REVIEW

**Comment by MaxGabriel** [comment]
Should the docs (“While this is simply a @WriterT@”) be updated too?

**Comment by snoyberg** [comment]
Hah, I didn't expect anyone to be reviewing this. Good catch. I'm not quite sure which (if any) of these experiments will end up making it onto master, so feedback on whether this is worth it at all is certainly welcome :). I'm currently experimenting with a pretty crazy subsite rewrite based on all of this, but it's not ready to be pushed, and I probably won't finish it until at least next week due to travel.

**Comment by psibi** [comment]
While you are doing some breaking changes, I think this is a good time to fix this also: https://github.com/yesodweb/yesod/issues/1418#issuecomment-315051642

**Comment by snoyberg** [comment]
Good call @psibi, added in 915d9e2f

**Pull request merged**
