### PR TITLE
add a runHttpRequest typeclass method

### PR DESCRIPTION
**Pull request by gregwebs**
I am trying to make it possible to handle HTTP failures in yesod-auth

### CODE REVIEW

**Comment by gregwebs** [comment]
The idea is that one can run this in a `try`, log the error, and retry the request. The reason that `Request` is passed as a parameter is so that it can be inspected in case that helps decide how to handle the failure.

**Comment by snoyberg** [comment]
It seems like a strange type signature. I'd have expected something like:

```haskell
runHttpRequest :: Request -> (Response BodyReader -> HandlerT master IO a) -> HandlerT master IO a
```

It just seems like the current signature may be slightly too limiting, e.g., what about adding in auto-retry logic?

**Comment by gregwebs** [comment]
My concept is that this is just for dealing with errors. So I don't want to make a friendlier API for modifying the response. I agree that this is a strange API for dealing with errors because there is nothing explicit in the types about errors, but I think this provides all the power one needs. Adding retry logic seems simple enough.

```
= try (doReq req) >>= either (doReq req) return
```

**Comment by snoyberg** [comment]
The problem is that such a signature will not allow distinguishing between rerunning the request and rerunning the user actions taken thereafter with the `Response`. That said, I don't feel strongly about this, if you want to keep this type signature, feel free to merge.

**Comment by gregwebs** [comment]
I actually think it is desirable to be able to run Handler code afterwards that concludes with `sendResponse` and sends something entirely different.

If that is what you were getting at? Before you said the type signature was too limiting but now you are saying it is not limiting enough? 

I am open to changing this, I just want to have something very extensible without having to program a ton of stuff. What would your default implementation be?

**Comment by snoyberg** [comment]
I guess "limiting" depends on who's side you're looking at ;)

I'm not sure that wrapping up `sendResponse` will work as expected, since it short-circuits by throwing an exception.

Anyway, my proposed implementation would be something like the following (not actually type checked):

```haskell
runHttpRequest :: Request -> (Response BodyReader -> HandlerT master IO a) -> HandlerT master IO a
runHttpRequest req inner = do
  man <- asks authHttpManager
  HandlerT $ \r -> withResponse req man $ \res -> unHandlerT (inner res) t
```

Which could be cleaned up if desired with monad-control, though explicit is kind of nice here.

**Comment by gregwebs** [comment]
@snoyberg updated with a compiling form of your suggestion

**Comment by snoyberg** [comment]
This introduces a breaking change by requiring HasHttpManager. While I think that's a good change, I'm not sure we want to bundle that in now. Afaict, it's possible to implement this without that superclass constraint.

**Comment by gregwebs** [comment]
good point. I changed the code to use http-client in the typeclass as per your original suggestion.

**Pull request merged**
