### PR TITLE
Revert 1 master

### PR DESCRIPTION
**Pull request by dschalk**
I published a yesod-websockets example along with some commentary explaining the example and the general usefulness of websockets at github.com/dschalk/yesod-websockets-schalk/Game-Example. I would be honored to see it incorporate it into the main yesodweb/yesod repository. I am open to suggestions for changes. 
I have code which computes all "impossibles" (see "Websockets_for_Browser_Control" in "Game-Example") but I thought that might be too extraneous for the yesod-websockets repository. Anyway, if you see value in my work and it is deemed appropriate for incorporation into the Yesod repository, please take it as it is, or tell me how you would like for me to proceed. -- David Schalk/schalkbox@gmail.com

### CODE REVIEW

**Comment by snoyberg** [comment]
This PR looks like it's including a lot of changes by mistake. Can you review and update it?

**Comment by dschalk** [comment]
I am having trouble with the Github site. The problem is, I don't know what I am doing. I will gladly review and update my request, but I fear I will only mess this up more. I would like for my work at github.com/dschalk/yesod-websockets-schalk/Game-Example to be added to github.com/yesodweb/yesod/yesod-websockets, if that would be appropriate. How to get my request into the customary pull request format, I do not know. Following the Github instructions hasn't worked for me. Do you happen to have guidelines for making pull requests?

**Comment by geraldus** [comment]
@dschalk, first of all you have to __fork__ `yesodweb/yesod` repository.
If you have GitHub app installed, you can fork repository from [mainpage](https://github.com/yesodweb/yesod) or use `FORK` on page (see upper right corner).

Now you have your own `yesod` repository and you need to clone it to your local machine. You can do this using `GitHub application`, `git` application (`git clone`),  or any other git GUI client. After you've clonned _your forked_ repository make changes to the code you want. It will be good to have separate code branch in your forked repository, e.g. `tmp-websockets-example`. Use this branch when commit your changes.

After you've commited your changes to your forked repository, you'll see pull `Compare and make pull request` button, when you visit your repository. Just click it and GitHub will do the rest.

Cheers!

**Comment by dschalk** [comment]
I forked the Yesod repository, added the “Game-Example” subdirectory with files that compile and run on my linux box, entered “git add . “ and also “git add -A” in my terminal, entered “git commit” and wrote a comment, and then entered “git push -u origin master”. I don't know if this is normal, but the repo at dschalk/yesod/yesod-websockets does not have the Game-Example subdirectory and files, just a hollow entity called “Game-Example”. The subdirectory and files are present at dschalk/yesod-websockets-schalk, but that is not a fork of yesodweb/yesod/yesod-websockets.

I don't know why I got the message “The Travis CI build could not complete due to an error “. I tried again this morning, and I did click the  "Compare and make pull request" button.

Thanks for helping me with this.

**Comment by dschalk** [comment]
By the way, I am not proposing to change anything. I am merely offering to contribute an example and some commentary which I think would be interesting and useful.
I don't know what I did to cause Github to think I an proposing to change 88 files, or that I want "to merge 2 commits into yesodweb:master from dschalk:revert-1-master, whatever that means.

**Comment by dschalk** [comment]
The files I am proposing to add to yesod-websockets are at https://github.com/dschalk/yesod/commit/b9bfb688db17b281759f7c29de9b97e2f882cc10

**Comment by creichert** [comment]
This issue was handled in a follow up PR. It would be nice to know when you create a follow up post.

**Pull request closed without merging**
