### PR TITLE
fixed: yesod-form: textareaField: writeHtmlEscapedChar: convert "\r\n" to "<br>" closed #1354

### LINKED ISSUE #1354: yesod-form: textareaField: writeHtmlEscapedChar: '\n' translate to "<br>", but http newline is "\r\n"
[yesod/Fields.hs at master · yesodweb/yesod](https://github.com/yesodweb/yesod/blob/master/yesod-form/Yesod/Form/Fields.hs#L229)
`textareaField` having `writeHtmlEscapedChar` is `'\n'` translate to `"<br>"`, but http newline is `"\r\n"`.
then, html contain junk `\r`.
this is spec? or bug?
I am sorry poor english. thank you.

### PR DESCRIPTION
**Pull request by ncaq**
fix #1354 .
I think solution to trim "\r".

### CODE REVIEW

**Comment by snoyberg** [comment]
Could you add a note to the changelog and make a patch version number bump?

**Comment by ncaq** [comment]
I commited.
Is this OK?

**Comment by snoyberg** [comment]
Yes, that's fine. The last issue is that there are build errors for older versions of GHC, e.g.: https://travis-ci.org/yesodweb/yesod/jobs/245673023#L525. This is due to `mempty` not being in scope.

**Comment by ncaq** [comment]
I fixed.

But, fail build job where `"env": "BUILD=cabal GHCVER=8.0.2` [Job #2416.3 - yesodweb/yesod - Travis CI](https://travis-ci.org/yesodweb/yesod/jobs/246050794)
travis log is `The job exceeded the maximum time limit for jobs, and has been terminated.`

The haskell stack build jobs succeed. 

I don't know solution to cabal build hell.

Please help me. thanks.

**Comment by psibi** [comment]
@ncaq I have restarted the build. I don't think this is cabal build hell. :-)

**Comment by MaxGabriel** [comment]
#1048 had the same issue. Not sure if there's a solution there or if it's just inherent slowness of the new GHC

**Comment by ncaq** [comment]
> @ncaq I have restarted the build. I don't think this is cabal build hell. :-)

I am mistake. This is not cabal hell.
This problem is not unrelated for dependencies.
But, cabal build to be `The job exceeded the maximum time limit for jobs, and has been terminated.`
Should I do?

> #1048 had the same issue. Not sure if there's a solution there or if it's just inherent slowness of the new GHC

Sorry, I don't understand to relationship.

**Comment by snoyberg** [comment]
Thanks! Ignoring that Travis failure; I've deleted caches to hopefully get it to succeed in the future.

**Pull request merged**
