### PR TITLE
Internationalize

### PR DESCRIPTION
**Pull request by StevenXL**
Before submitting your PR, check that you've:

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddocks for new, public APIs

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by StevenXL** [comment]
Please see #686 and #1593.

The type of `fsAttrs` (in the `FieldSettings` data type) does not reflect the full semantics of HTML attributes. This pull request changes the type of `fsAttrs` from `[(Text, Text)]` to `[(Text, [SomeMessage master])]`. 

The change of the second element of the tuple to a list allows us to express the idea that an attribute can have multiple values. For example: `<input class="rounded orange"/>`. 

The use of `SomeMessage master` allows the user to provide to use some value that we can, later on, internationalize.

**Comment by StevenXL** [comment]
Also, I am wary about `removeClass`, given the definition of [SomeMessage](https://hackage.haskell.org/package/shakespeare-2.0.20/docs/src/Text.Shakespeare.I18N.html#SomeMessage). We can't compare values of type `SomeMessage` for equality, because the type system has lost information about what data type the `SomeMessage` data constructor holds. So `removeClass` does not make sense.

Should we update `SomeMessage master` to:

```
data SomeMessage master msg where
    SomeMessage :: (Eq msg, RenderMessage master msg) => msg -> SomeMessage master msg

fromSomeMessage :: SomeMessage master msg
fromSomeMessage (SomeMessage msg) = msg
```

I'm not sure what can of worms I'd be opening up at that point.

**Comment by snoyberg** [comment]
I'm not really bought in on this. You've identified at least one issue above. I still don't see the major issue with forcing the caller to render to `Text` before including in the `fsAttrs`.

**Comment by StevenXL** [comment]
@snoyberg I agree with you. I think the changes required to make this change are not worth it. I will close down the PRs as well as the issue. We can revisit this problem if the issue comes up again.

**Pull request closed without merging**
