### PR TITLE
Don't keep partial autogen file when exception occurs

### PR DESCRIPTION
**Pull request by paul-rouse**
The problem is this: an (async) exception occurring while an autogen file was being written resulted in an incomplete file being left behind.  When it was checked again - even after rebuilding the code - the hash matched and the partial content was served.  The solution is simply to delete the file on any exception.

#1291 had rather odd symptoms because of this, presumably because of something like a ctrl-C while minifying was taking a ridiculous time to complete.

### CODE REVIEW

**Comment by snoyberg** [comment]
This looks fine, but what's really funny is that I'm working on a function to do something very similar for this in conduit-extra.

**Comment by paul-rouse** [comment]
Maybe a more general solution is the answer, then.

**Comment by snoyberg** [comment]
I'll share the function here in a moment, but the basic idea is: a conduit version of the cautious-file package.

**Comment by snoyberg** [comment]
Here's the commit

**Comment by psibi** [comment]
@snoyberg I think you might have missed the commit.

**Comment by snoyberg** [comment]
Doh, thanks. https://github.com/snoyberg/conduit/commit/73b5fc28f1bb3ae52095c404ff64f07ba0da92ac

**Comment by paul-rouse** [comment]
Oh yes - it's nice that it handles pulling the plug as well.  I am happy to try using conduit instead in addStaticContentExternal, but give me a couple of days - I have some real work to do for the rest of today and tomorrow!

**Comment by snoyberg** [comment]
No pressure, Using cautious-file is also an option here, though we already
have the conduit dependency, so that might be better. I'm just blown away
that I got the notification on your work here as I was writing the test
case.

**Comment by paul-rouse** [comment]
Yes it is quit a coincidence!  I might as well use it, since you've written it!

**Comment by paul-rouse** [comment]
Here it is, revised to use sinkFileCautious

**Comment by snoyberg** [comment]
Awesome, I tweaked the stack.yaml a bit, merged, and released. Thanks!

**Comment by paul-rouse** [comment]
Did you mean/expect it still to be in a branch on github? And sorry I didn't look harder at the tests!

**Comment by snoyberg** [comment]
Good catch, I pushed to master. (Second time I've made that mistake this
week...)

**Pull request merged**
