### PR TITLE
Replace HandlerT with HandlerFor in the documentation

### PR DESCRIPTION
**Pull request by jeffhappily**
Fixes https://github.com/yesodweb/yesod/issues/1696

Before submitting your PR, check that you've:

- [x] Bumped the version number
- [ ] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [ ] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddocks for new, public APIs

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by jeffhappily** [comment]
Quick question, should I also update the Changelog and bump the version?

**Comment by snoyberg** [comment]
Great changes, thanks!

> Quick question, should I also update the Changelog and bump the version?

That would be awesome.

**Comment by jeffhappily** [comment]
For both `yesod-core` and `yesod-eventsource` ?

**Comment by snoyberg** [comment]
Yes please

**Review by snoyberg — APPROVED** [review]
Thanks!

**Pull request merged**
