### PR TITLE
yesod-bin: Make it build with latest optparse-applicative

### PR DESCRIPTION
**Pull request by erikd**
Also bump dependency lower bound.

### CODE REVIEW

**Comment by snoyberg** [comment]
I'd rather keep compatibility with older versions. Would it be possible to update this with a CPP approach?

**Comment by erikd** [comment]
According to Travis, the latest `optparse-applicative` breaks criterion, so maybe an upper bound makes more sense.

**Comment by erikd** [comment]
I switched to a CPP fix as suggested.

There was one failure:
```
Codec.Compression.Zlib: compressed data stream format error (incorrect data check)
```
which has nothing to do with my change.

**Comment by snoyberg** [comment]
Awesome, thanks!

**Pull request merged**
