### PR TITLE
Add instance of MonadHandler and MonadWidget for ExceptT

### PR DESCRIPTION
**Pull request by Dridus**
I noticed there aren't any lifting instances for ExceptT like there are for ErrorT. Hopefully it's uncontroversial to add them, but let me know if I should approach this with a different process.

### CODE REVIEW

**Comment by snoyberg** [comment]
There's a build failure with GHC 7.8.4. Can you either use CPP to avoid those instances on older transformers, or use transformers-compat?

**Comment by Dridus** [comment]
Ah whoops, sorry about that. I pushed a new commit which makes them conditional on `__GLASGOW_HASKELL__ >= 710`, hopefully that's acceptable.

**Comment by snoyberg** [comment]
The condition should really be on the transformers package itself, not GHC.
It is possible to force different versions.

**Comment by Dridus** [comment]
okay, I'll change it to `MIN_VERSION_transformers(0,4,0)`. I didn't previously realize that was possible.

**Comment by Dridus** [comment]
okay, I think this latest commit addresses that. let me know if it's suitable

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
