### PR TITLE
Add UserName message constructor

### PR DESCRIPTION
**Pull request by geraldus**

### CODE REVIEW

**Comment by geraldus** [comment]
Travis failed with following errors:
7.8.4:
> cabal: /home/travis/.cabal/logs/transformers-base-0.4.4.log: does not exist

7.10.1
> cabal: /home/travis/.cabal/logs/network-2.6.2.1.log: does not exist

**Comment by snoyberg** [comment]
Can you apply the advice from this blog post?

http://www.yesodweb.com/blog/2015/07/s3-hackage-mirror-travis

I just noticed this problem with Hackage on another repo

**Comment by geraldus** [comment]
@snoyberg, surely, already in progress, meanwhile can you give some comments, for example:
* should "User Name" become "User name"?
* what about suffixes -- I can drop this commit or make convert suffixes to lowercase.

**Comment by geraldus** [comment]
Ok, Travis done.

**Comment by snoyberg** [comment]
I like UserName. I'm not sure what you mean be suffixes though, can you clarify? The other changes seem fine too, if that's what you mean.

**Comment by geraldus** [comment]
@snoyberg, hm, maybe I should say postfixes (I'm not sure).  I'm talking about these changes:
"Login" → "Log In". So, should I convert "In"s and "Out"s to lowercase?

**Comment by gregwebs** [comment]
If it is a title that would indicate to me that all the words should be upper cased. But I don't think there is a right or wrong answer here.

**Comment by geraldus** [comment]
@snoyberg @gregwebs 
Also, maybe we should introduce `LogoutTitle` message which is the same as existing `Logout` for the sake of consistency (and deprecate the latter).

_Initially I wanted to introduce `Login` message for input's label, but then I've found that this may confuse users, fortunatelly I quicky found `UserName` as replacement._

**Comment by gregwebs** [comment]
makes sense to me. But @snoyberg may take issue with a breaking change. Perhaps keep the existing constructor and point it to the new one?

**Comment by snoyberg** [comment]
I'm OK with introducing new constructor for this without bumping the major version number.

**Comment by geraldus** [comment]
Done, please review everything once again.

**Comment by snoyberg** [comment]
Thanks!

**Comment by geraldus** [comment]
@lubomir , I've created [another PR](https://github.com/yesodweb/yesod/pull/1102) for this.

**Pull request merged**
