### PR TITLE
Fixes for merge conflicts

### PR DESCRIPTION
**Pull request by seanwestfall**
Hey @snoyberg, I was wondering if I could continue @gregwebs PR https://github.com/yesodweb/yesod/pull/1004: _yesod-core has no dependency on the shakespeare_ package? This PR just fixes the merge conflicts and updates the core-without-shakespeare with master.

### CODE REVIEW

**Comment by snoyberg** [comment]
@gregwebs You have any objection to merging this into that branch?

I'll be honest about outlook on this: I'm not particularly enthusiastic about making this change. I've long ago given up on the dependency game, and I don't relish the thought of breaking backwards compatibility for this.

**Comment by seanwestfall** [comment]
@snoyberg Just read your _Enough with Backwards Compatibility_ blog post. I'm not even sure if what you read was _for_ or _against_ backwards compatibility. Though, I was just about to complain every time I update yesod there are breaking changes.. 

I'm not sure if this change would even involve a breaking change. Doesn't the work just entail going through the code base and replacing all the Hamlet code with plain HTML? I always thought it made more sense that Hamlet would be more of an optional dependency than a requirement. And it's possible to do this without introducing a breaking change, Yesod can work with both plain HTML and Hamlet, without having to explicitly import a Hamlet lib.

Right now I'm going through all the test cases to get this to pass all checks, update coming shortly.

**Comment by snoyberg** [comment]
That blog post was an April fools post, I'm very much in favor of backwards
compatibility. I'm not sure which changes you've experienced recently in
Yesod; yesod-core 1.4 was released in September of 2014, and to my
knowledge has had no breaking changes since then.

**Comment by gregwebs** [comment]
I do think this branch should definitely get merged and yesod should release a new major version. The PR describes the effects to end users which should be minimal for most users.

**Comment by seanwestfall** [comment]
Sorry @snoyberg, your humor is too advanced for me...
Quick question about the AppVeyor and Travis CI checks: Do I have to build yesod-core-1.4.33 with ghc-7.10.3 to get the same matching errors that are shown on AppVeyor.

@gregwebs This pastebin has a grep of where all the hamlet templates are declared: https://pastebin.com/XMmT5qgY There are currently 136 hamlet templates in yesodweb/yesod. In order to finish the work we'd just have convert the rest of them to standard HTML.

**Comment by gregwebs** [comment]
Using `-ddump-splices` or `-ddump-to-file` can help with the down-compilation. Potentially we can keep the shakespeare version in comments.

**Comment by jezen** [comment]
Closing due to extensive inactivity.

**Pull request closed without merging**
