### PR TITLE
languages reflects setLanguage

### PR DESCRIPTION
**Pull request by snoyberg**

### CODE REVIEW

**Comment by snoyberg** [comment]
I haven't heard any yays or nays on this yet, so leaving blocked for now.

**Comment by paul-rouse** [comment]
Speaking for myself, it won't have any adverse effect - which hardly seems worth saying, except that if everyone thinks that way, no-one says anything!

**Comment by psibi** [comment]
Agree with Paul here. But, I can say `yay` anyway. :)

**Comment by snoyberg** [comment]
Exactly the feedback I needed, thanks 👍

**Pull request merged**
