### PR TITLE
Simple auth plugin for hardcoded auth entities

### PR DESCRIPTION
**Pull request by geraldus**
I'm not sure if this will be useful for someone, feel free to reject this module.
Would be happy to have any comments on this.

### CODE REVIEW

**Comment by gregwebs** [comment]
Thanks. Can't you have a default definition for isUserExists ?

**Comment by geraldus** [comment]
@gregwebs I have clear idea about this.  I think it is possible if `YesodAuthHardcoded` class will contain one extra property, let's say `hadrcodedUsers :: [AuthHardcodedLogin site]`.  What do you think?

Also, I see now that `HardcodedCreds` data type is redundant in current implementation.

**Comment by geraldus** [comment]
I've tried to implement such class property _(what is the right word -- operation?)_ as a `Map`, e.g.

```haskell
class (YesodAuth site) => YesodAuthHardcoded site where
  type AuthHardcodedLogin site

  -- | A list of all hardcoded uses names.
  hardcodedUsers :: Map.Map Text (AuthHardcodedLogin site)
  hardcodedUsers = Map.empty

  isUserNameExists username =
    return
      (case Map.lookup username hardcodedUsers of
         Nothing -> False
         Just  _ -> True)

```

But this way gives ambiguity when trying to get this list in `isUserExists` function.

> Could not deduce (YesodAuthHardcoded site0)
>   arising from a use of ‘hardcodedUsers’
> from the context (YesodAuthHardcoded site)
>   bound by the class declaration for ‘YesodAuthHardcoded’
>   at …
> The type variable ‘site0’ is ambiguous
> In the second argument of ‘Map.lookup’, namely ‘hardcodedUsers’
> In the expression: Map.lookup username hardcodedUsers
> In the first argument of ‘return’, namely
>  …

I believe this will be solved if I add extra param for both functions:

```haskell
hardcodedUsers :: site -> Map.Map Text (AuthHardcodedLogin site)
isUserNameExists :: site -> Text -> HandlerT site IO Bool
```

But, maybe you talking about simplest way?  I could think about database check, but this requires one extra constraint to class -- `YesodAuthPersist`.

**Comment by geraldus** [comment]
Ok, I think it is good point, that `isUserExists` should take `site` argument.  What about this?

```haskell
class (YesodAuth site) => YesodAuthHardcoded site where
  type AuthHardcodedLogin site

  -- | A list of all hardcoded uses names.
  hardcodedUsers :: site -> Set.Set Text
  hardcodedUsers _ = Set.empty

    -- | Check whether given user name exists among hardcoded names.
  isUserNameExists :: site -> Text -> HandlerT site IO Bool
  isUserNameExists site = return . flip Set.member (hardcodedUsers site)

  -- | Validate given user name with given password.
  validatePassword :: Text -> Text -> HandlerT site IO Bool

```

**Comment by geraldus** [comment]
What about this?

```haskell
class (YesodAuth site) => YesodAuthHardcoded site where
  type AuthHardcodedLogin site

  -- | A list of all hardcoded uses names.
  hardcodedUsers :: site -> Map.Map Text (AuthHardcodedLogin site)
  hardcodedUsers _ = Map.empty

  -- | Check whether given user name exists among hardcoded names.
  isUserNameExists :: site -> Text -> HandlerT site IO Bool
  isUserNameExists site username =
    do mayUser <- getUser site username
       return (maybe False (const True) mayUser)

  -- | Return user entity by its name.
  getUser :: site -> Text -> HandlerT site IO (Maybe (AuthHardcodedLogin site))
  getUser site username = return (Map.lookup username (hardcodedUsers site))

  -- | Validate given user name with given password.
  validatePassword :: Text -> Text -> HandlerT site IO Bool

```

**Comment by gregwebs** [comment]
Ahh, I think I wasn't really understanding things when I asked that question. My suggestion would be

``` haskell
isUserNameExists :: Text -> HandlerT site IO Bool
```

**Comment by gregwebs** [comment]
Ahh, I think I wasn't really understanding things when I asked that question. My suggestion would be

``` haskell
isUserNameExists :: Text -> HandlerT site IO Bool
isUserNameExists _ = return False
```

**Comment by gregwebs** [comment]
For these typeclass configurations it is better to have a few general, flexible, easy to understand functions than lots of little functions.

Also, it would be better to rename to `doesUserNameExists`

**Comment by mrkkrp** [comment]
Maybe even `doesUserNameExist`.

**Comment by geraldus** [comment]
Ok, I've simplified a class and removed all default implementations.

**Comment by geraldus** [comment]
@gregwebs I've updated documentation and tested this plugin locally.

**Comment by gregwebs** [comment]
Thanks! Why does this require MonadThrow ?

**Comment by geraldus** [comment]
@gregwebs I have no idea, I wanted to put login widget in top level, and type signature inferred by GHC contains this constraint.  But it is possible not to depend on `exceptions` package and avoid `MonadThrow` constraint by moving widget definition in `where` block.  I've updated code.

**Comment by gregwebs** [comment]
thanks! This is on hackage now

**Pull request merged**
