### PR TITLE
Add hook to apply arbitrary function to all handlers

### PR DESCRIPTION
**Pull request by pseudonom**
You can see some of the motivation for this change in:

https://github.com/pseudonom/indexed-yesod
https://groups.google.com/forum/#!topic/yesodweb/gFqkVHKBB0s

### CODE REVIEW

**Comment by snoyberg** [comment]
It looks like the Travis build is failing. Were the test suites passing locally?

**Comment by pseudonom** [comment]
Whoops. Fixed now.

**Comment by snoyberg** [comment]
Looks good to me. @gregwebs any objections to merging this?

**Comment by snoyberg** [comment]
Thanks!

**Comment by pseudonom** [comment]
Thanks! Any guess as to when it will end up on hackage/stackage?

**Comment by snoyberg** [comment]
Just uploaded.

**Pull request merged**
