### PR TITLE
defaultErrorHandler causes inappropriate 406 reponses

### PR DESCRIPTION
**Pull request by whittle**
Issue originally raised at https://groups.google.com/forum/#!topic/yesodweb/ed6MvRG_pVg

### CODE REVIEW

**Comment by whittle** [comment]
Currently only adds failing specs. PR created per @snoyberg’s request on #1402. I am currently examining options for fixing the issue.

**Comment by snoyberg** [comment]
Thanks for following up on this. Based on your comments, I'm going to hold off until I see another ping from you on this. If there's something you'd like me to chime in with before, let me know.

**Comment by StevenXL** [comment]
@whittle I've been trying to make the tests on this pass. While there are several different ways to get the correct status (each with different tradeoffs), the tests expect no `content-type` header, which is a bit trickier. 

I was wondering if you'd like to pair on this PR?

**Comment by StevenXL** [comment]
See #1540

**Pull request closed without merging**
