### PR TITLE
JSON-specific sendResponseStatus

### PR DESCRIPTION
**Pull request by bitemyapp**
Addressing #1101 

Name is a little verbose. Not married to this method of dealing with this problem.

### CODE REVIEW

**Comment by gregwebs** [comment]
This saves typing `to` with the goal of providing documentation.
The only thing one can send is a response, so I would favor `sendStatusJson`.

**Comment by bitemyapp** [comment]
@gregwebs I like that. I will update it accordingly.

**Comment by snoyberg** [comment]
I'm good with this. I'll wait for @gregwebs to merge since he had made some comments.

**Comment by gregwebs** [comment]
thanks! Sorry for the delay

**Pull request merged**
