### PR TITLE
Fix subsite-to-subsite dispatch

### LINKED ISSUE #1803: `mkYesodSubDispatch` doesn't seem to work with nested subsites
I'm trying to write a Yesod subsite which bundles its own static assets. The `yesod-static` package normally works well for managing static assets, but it is a subsite, and it seems nesting a subsite within another subsite doesn't work with the current `mkYesodSubDispatch` TH function.

Here is a minimal example which mostly follows the example in the [Yesod book](https://www.yesodweb.com/book/creating-a-subsite). I have also put this example together into [a repository](https://github.com/jezen/subsite-with-static).

```haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE ViewPatterns #-}

module Subsite.Data where

import ClassyPrelude
import Yesod
import Yesod.Static

{- HLINT ignore "Use newtype instead of data" -}
data Subsite = Subsite
  { getStatic :: Static
  }

mkYesodSubData "Subsite" [parseRoutes|
/ SubHomeR GET

-- TODO: Make this subsite work
-- /static StaticR Static getStatic
|]

newSubsite :: MonadIO m => m Subsite
newSubsite = Subsite <$> liftIO (static "static")
```

```haskell
{-# OPTIONS_GHC -fno-warn-orphans #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE ViewPatterns #-}

module Subsite
  ( module Subsite.Data
  , module Subsite
  ) where

import ClassyPrelude
import Subsite.Data
import Yesod

getSubHomeR :: Yesod master => SubHandlerFor Subsite master Html
getSubHomeR = liftHandler $ defaultLayout $ do
  -- TODO: Swap this remote stylesheet for the local one
  addStylesheetRemote "https://necolas.github.io/normalize.css/8.0.1/normalize.css"
  -- TODO: Make this work
  --addStylesheet $ StaticR css_normalize_css
  [whamlet|Welcome to the subsite!|]

instance Yesod master => YesodSubDispatch Subsite master where
  yesodSubDispatch = $(mkYesodSubDispatch resourcesSubsite)
```

```haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}

module Main where

import ClassyPrelude hiding (Handler)
import Subsite
import Yesod
import Yesod.Core.Types

{- HLINT ignore "Use newtype instead of data" -}
data App = App
  { getSubsite :: Subsite
  }

mkMessage "App" "messages" "en"

mkYesod "App" [parseRoutes|
/ HomeR GET
/sub SubsiteR Subsite getSubsite
|]

getHomeR :: Handler Html
getHomeR = do
  now <- liftIO getCurrentTime
  defaultLayout
    [whamlet|<p>The time now is: #{tshow now}|]

instance Yesod App where

makeFoundation :: IO App
makeFoundation = App <$> newSubsite

main :: IO ()
main = makeFoundation >>= warp 3000

makeApplication :: App -> IO Application
makeApplication foundation = do
  appPlain <- toWaiAppPlain foundation
  return $ defaultMiddlewaresNoLogging appPlain

getApplicationRepl :: IO (Int, App, Application)
getApplicationRepl = do
  foundation <- makeFoundation
  app1       <- makeApplication foundation
  return (3000, foundation, app1)

shutdownApp :: App -> IO ()
shutdownApp _foundation = pure ()
```

---

When I uncomment this line in the routes:

```
 /static StaticR Static getStatic
```

…the compiler blows up like this:

```
src/Subsite.hs:28:23: error:
    • Couldn't match type: SubHandlerFor Subsite master0 content0
                     with: HandlerFor Subsite TypedContent
      Expected: Yesod.Core.Types.ParentRunner Subsite
        Actual: SubHandlerFor Subsite master0 content0
                -> Yesod.Core.Types.YesodSubRunnerEnv Subsite master0
                -> Maybe (Route Subsite)
                -> Application
    • In the first argument of ‘\ parentRunner_an3k
                                  getSub_an3l
                                  toParent_an3m
                                  env_an3n
                                  -> yesodSubDispatch
                                       Yesod.Core.Types.YesodSubRunnerEnv
                                         {Yesod.Core.Types.ysreParentRunner = parentRunner_an3k,
                                          Yesod.Core.Types.ysreGetSub = getSub_an3l,
                                          Yesod.Core.Types.ysreToParentRoute = toParent_an3m,
                                          Yesod.Core.Types.ysreParentEnv = env_an3n}’, namely
        ‘yesod-core-1.6.24.2:Yesod.Core.Class.Dispatch.subHelper’
      In the expression:
        (((((\ parentRunner_an3k getSub_an3l toParent_an3m env_an3n
               -> yesodSubDispatch
                    Yesod.Core.Types.YesodSubRunnerEnv
                      {Yesod.Core.Types.ysreParentRunner = parentRunner_an3k,
                       Yesod.Core.Types.ysreGetSub = getSub_an3l,
                       Yesod.Core.Types.ysreToParentRoute = toParent_an3m,
                       Yesod.Core.Types.ysreParentEnv = env_an3n})
              yesod-core-1.6.24.2:Yesod.Core.Class.Dispatch.subHelper)
             (\ sub_an3o -> getStatic sub_an3o))
            (\ sroute_an3p -> StaticR sroute_an3p))
           env9189_an3e)
          (((\ p_an3i r_an3j
               -> r_an3j {Network.Wai.Internal.pathInfo = p_an3i})
              restPath_an3h)
             req9189_an3f)
      In an equation for ‘helper9189_an3g’:
          helper9189_an3g ((:) "static" restPath_an3h)
            = (((((\ parentRunner_an3k getSub_an3l toParent_an3m env_an3n
                     -> yesodSubDispatch
                          Yesod.Core.Types.YesodSubRunnerEnv
                            {Yesod.Core.Types.ysreParentRunner = parentRunner_an3k,
                             Yesod.Core.Types.ysreGetSub = getSub_an3l,
                             Yesod.Core.Types.ysreToParentRoute = toParent_an3m,
                             Yesod.Core.Types.ysreParentEnv = env_an3n})
                    yesod-core-1.6.24.2:Yesod.Core.Class.Dispatch.subHelper)
                   (\ sub_an3o -> getStatic sub_an3o))
                  (\ sroute_an3p -> StaticR sroute_an3p))
                 env9189_an3e)
                (((\ p_an3i r_an3j
                     -> r_an3j {Network.Wai.Internal.pathInfo = p_an3i})
                    restPath_an3h)
                   req9189_an3f)
   |
28 |   yesodSubDispatch = $(mkYesodSubDispatch resourcesSubsite)
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed, one module loaded.
(0.68 secs,)
```

I _think_ this is because `YesodSubRunnerEnv` is getting the wrong value for (perhaps) `ysreParentRunner`. I also suspect this is related to https://github.com/yesodweb/yesod/issues/1002 because of @andrewthad's comment.

> I occasionally build subsites without using yesod's routing TH (to get **non-monomorphic routes**)

### PR DESCRIPTION
**Pull request by AriFordsham**
Before submitting your PR, check that you've:

- [X] Bumped the version number

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

Fixes #1803 .

It is now behaving correctly on https://github.com/jezen/subsite-with-static (see https://github.com/AriFordsham/subsite-with-static/tree/ari/yesod-change).

It's a bit messier than I wuld like, as well as being a hack overall - see https://github.com/yesodweb/yesod/issues/1803#issuecomment-1605988275. The type signature to `subTopDispatch` makes sure this builds when `mkDispatchInstance` passes `subHelper` to it (even though `subHelper` is unused ☹)

### CODE REVIEW

**Review by snoyberg — COMMENTED** [review]
I can't really claim a lot of familiarity with this code anymore, it's been a while, but the overall approach seems valid. I'd recommend including a test case to demonstrate that this is working. And if all the existing test cases pass, I think that's a good sign that it's working as expected.

**Comment by AriFordsham** [comment]
A fails-before, passes-after test is hard to write, because the failure is compile-time. I guess I could just include a simple test which show subsite-to-subsite dispatch working.

**Comment by jezen** [comment]
I think that sounds sensible 🙂

**Comment by AriFordsham** [comment]
Added a test case. This does not compile on master, and passes on this PR.

**Review by snoyberg — APPROVED** [review]
Thank you!

**Pull request merged**
