### PR TITLE
Move yesod-test to using the term "token" instead of nonce.

### PR DESCRIPTION
**Pull request by MaxGabriel**
I also considered `addCsrfToken` but I found it super hard to type, and it seems like the rest of Yesod just uses token as well (with the exception of Yesod.Auth.GoogleEmail2).

Addresses part 1 of #914

Edit: would you like me to update the changelog when I make a PR? I know some projects just go through commits when they make a release and others put new changes into a "master" section of the changelog that later gets moved to a specific version number.

### CODE REVIEW

**Comment by snoyberg** [comment]
@MaxGabriel Would you be able to rebase these changes to be compatible with the other PR?

**Comment by MaxGabriel** [comment]
@snoyberg Yes I would. I'll also update the documentation based on these changes

**Comment by MaxGabriel** [comment]
@snoyberg Ok, I've rebased against master and updated the documentation to talk about tokens.

**Comment by snoyberg** [comment]
Beautiful, thank you!

**Pull request merged**
