### PR TITLE
Update license to 2017

### PR DESCRIPTION
**Pull request by madnight**

### CODE REVIEW

**Comment by snoyberg** [comment]
Thanks!

**Comment by erikd** [comment]
Isn't that dat date the copyright date? What happens to the copyright on the work you did before this year? Are you giving that up?

I suspect that what you really want is to have a copyright date of `2012-2017`.

**Comment by madnight** [comment]
@erikd git solves that problem, for example if you check out a source code version of 2012, then the copyright year should be 2012 and so on (works well if you update every year), but your solution is also very common and equally valid

**Comment by psibi** [comment]
But for copyright the year that is mentioned in it should be the year on which it was released. So the year in the current Yesod LICENSE file isn't right, I think. For evolving products like software, a year range is typically used.

Reference: http://www.copyrightlaws.com/international/522/

**Comment by snoyberg** [comment]
I've updated the LICENSE file with a range.

**Pull request merged**
