### PR TITLE
Contexts can be parsed and included in instances. Standalone deriving…

### PR DESCRIPTION
**Pull request by jprider63**
… is used when a context is provided. Type variables can be included in routes/TH.

### CODE REVIEW

**Comment by snoyberg** [comment]
LGTM. Can you add a comment to the changelog explaining the changes and make a minor version bump in the cabal file?

**Comment by jprider63** [comment]
Done. For some reason Travis didn't test the second commit. I fixed an issue so it should work with old versions of template-haskell as well.

**Comment by psibi** [comment]
@jprider63 Can you document about how to use this new feature either in the cookbook https://github.com/yesodweb/yesod-cookbook or the yesod book if it's too much work ?

**Comment by jprider63** [comment]
Sure, I can add an example to the cookbook when I have some time. Would an example subsite with type variables and contexts make sense?

**Comment by psibi** [comment]
Yeah, that should do.

**Comment by jprider63** [comment]
I just added the example to the cookbook and created a [pull request](https://github.com/yesodweb/yesod-cookbook/pull/32).

**Comment by jprider63** [comment]
Is there anything else you'd like me to do before merging this?

**Comment by psibi** [comment]
@jprider63 There seems to be merge conflict with the PR.

**Comment by jprider63** [comment]
The changelog changed since I wrote this. I've bumped the version and fixed the conflict.

**Comment by psibi** [comment]
@snoyberg Can this be merged ?

**Comment by snoyberg** [comment]
LGTM, thanks!

**Pull request merged**
