### PR TITLE
Add Facebook oauth Authentication

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by snoyberg** [comment]
How is this intended to differ from yesod-auth-fb? https://www.stackage.org/package/yesod-auth-fb

**Comment by psibi** [comment]
Didn't know the existence of the package! Had to write this module to
handle Facebook authentication in one of the projects I was developing.

**Comment by snoyberg** [comment]
Is there a reason to add this to yesod-auth vs just referring to the external package? Pinging @meteficha for feedback as well.

**Comment by psibi** [comment]
@snoyberg This module closely follows the API of GoogleEmail2 module. But I don't think fragmentation and duplication is worth it. I looked into yesod-auth-fb and it also does the same thing but with a different design. But there are certain differences which right now makes me unable to use it:

* I cannot logout using `<a href=@{AuthR LogoutR}>Logout`. It just redirects to the login page to me without logging out. Is this a bug or am I missing something ?
* I tried to logout using `<a href=@{AuthR facebookLogout}>Facebook logout` and it's logging out my facebook login (as documented) but also redirects my page to facebook logout page. 

My requirement is this: I just need to logout my web application (and not logout  of facebook). Is that possible using `yesod-auth-fb`.

@meteficha   what do you think ?

This is a sample code demonstrating the problem:

```
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE QuasiQuotes           #-}
{-# LANGUAGE TemplateHaskell       #-}
{-# LANGUAGE TypeFamilies          #-}
import           Data.Default                (def)
import           Data.Text                   (Text)
import           Network.HTTP.Client.Conduit (newManager, Manager)
import           Yesod
import           Yesod.Auth
import           Yesod.Auth.BrowserId
import           Yesod.Auth.GoogleEmail2
import Yesod.Facebook
import Yesod.Auth.Facebook.ServerSide
import Facebook (Credentials(..))
import Network.HTTP.Client.TLS (tlsManagerSettings)

-- Replace with Google client ID.
clientId :: Text
clientId = "sample_google_client_id"

-- Replace with Google secret ID.
clientSecret :: Text
clientSecret = "sample_google_secret_id"

fbclientId :: Text
fbclientId = "sample_fb_client_id"

fbclientSecret :: Text
fbclientSecret = "sample_fb_client_secret_id"

data App = App
    { httpManager :: Manager
    }Would like to hear what Felipe has to say on this.

mkYesod "App" [parseRoutes|
/ HomeR GET
/auth AuthR Auth getAuth
|]

instance Yesod App where
    -- Note: In order to log in with BrowserID, you must correctly
    -- set your hostname here.
    approot = ApprootStatic "http://localhost:3000"

instance YesodFacebook App where

    fbCredentials _ = Credentials "yesod" fbclientId fbclientSecret
    fbHttpManager = httpManager


instance YesodAuth App where
    type AuthId App = Text
    getAuthId = return . Just . credsIdent

    loginDest _ = HomeR
    logoutDest _ = HomeR

    authPlugins _ =
        [ authBrowserId def
        , authGoogleEmail clientId clientSecret
        , authFacebook ["user_about_me", "email"]
        ]

    authHttpManager = httpManager

    -- The default maybeAuthId assumes a Persistent database. We're going for a
    -- simpler AuthId, so we'll just do a direct lookup in the session.
    maybeAuthId = lookupSession "_ID"

instance RenderMessage App FormMessage where
    renderMessage _ _ = defaultFormMessage

getHomeR :: Handler Html
getHomeR = do
    maid <- maybeAuthId
    defaultLayout
        [whamlet|
            <p>Your current auth ID: #{show maid}
            $maybe _ <- maid
                <p>
                    <a href=@{AuthR LogoutR}>Logout
                    <a href=@{AuthR facebookLogout}>Facebook logout
            $nothing
                <p>
                    <a href=@{AuthR LoginR}>Go to the login page
        |]

main :: IO ()
main = do
    man <- newManager
    warp 3000 $ App man

```

Let me know if you want the facebook secret id. I will mail it for testing purposes.

**Comment by psibi** [comment]
Any updates on this ? I have to use a forked version of yesod-auth because of this.

**Comment by snoyberg** [comment]
Let's give @meteficha another day in case the previous bumps were dropped, otherwise I'll merge. Sound good?

**Comment by psibi** [comment]
Thanks, I will check `yesod-auth-fb` once again to see if I haven't missed anything and comment here again.

**Comment by psibi** [comment]
I'm closing this PR as I was able to achieve the same thing via yesod-auth-fb. But I'm concerned about the maintenance of the package.

**Pull request closed without merging**
