### PR TITLE
Added Multi Input Form Functionality

### PR DESCRIPTION
**Pull request by Burtannia**
The current "MassInput" module requires that the form be resubmitted each time the user wishes to add an extra input field. The "MultiInput" module allows the user to add a new field by clicking a button without needing to submit the form. The programmer can specify a minimum number of inputs that they want the user to submit.

I was unsure whether this should be its own module or be part of MassInput so if it makes more sense to merge the two modules then that can be done.

There is currently no option to add a delete button next to each entry. It is possible to delete an entry in the list by simply leaving that particular input blank although this is not particularly intuitive.

------------------------------------------------

Before submitting your PR, check that you've:

- [X] Bumped the version number
- [X] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [X] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddocks for new, public APIs

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by Burtannia** [comment]
I'll deal with the failing CI issues tomorrow.

**Comment by Burtannia** [comment]
The failed CI tests are caused by no ToJavascript instances in the older versions of shakespeare. I'm trying to fix them but it's a little difficult because I can't get the project to resolve dependencies for older LTS version on my machine.

**Comment by snoyberg** [comment]
Not sure if you saw it, but there's a `stack-lts-9.yaml` file which includes necessary extra-deps for LTS 9.X. You can build with `stack test --stack-yaml stack-lts-9.yaml`.

**Comment by snoyberg** [comment]
Also, I think you want to `s/#ifdef MIN_VERSION/#if MIN_VERSION`.

**Comment by Burtannia** [comment]
@snoyberg I was trying with the `stack-lts-9.yaml` file but I'm still getting "Plan construction failed." on Windows. Building through an Ubuntu virtual machine is working fine though. I've now implemented the instances using `ifdef MIN_VERSION` etc. Turns out the problem was my use of indentation inside the original `ifdef`.

**Comment by Burtannia** [comment]
@snoyberg I believe the only failed test this time was due to a timeout.

**Comment by snoyberg** [comment]
Agreed on the CI failure.

With new APIs like this, my tendency is to say they should start in a separate library, so that if necessary, they can evolve more quickly without forcing a major version bump on the relatively more stable parts of the library. I'd be open to that library living in this repo, or in a separate one. Also, if there's a strong motivation for including it directly in yesod-form instead, please let me know.

**Comment by Burtannia** [comment]
I'm happy for it to be its own library. Remaining in this repository would probably be convenient unless there's a good reason for it to live in another one.

Do you have any thoughts on how it should relate to the existing `MassInput` module?

**Comment by snoyberg** [comment]
I honestly don't have any thoughts. I haven't used that module in a _very_ long time.

**Comment by Burtannia** [comment]
My current intention is to make the new `MultiInput` module its own library within this repository and add a note in the documentation of the existing `MassInput` that notes the existence of the new library. If/when the new library supports adding a delete button to fields like the old module does then we could discuss deprecating the old functionality.

**Comment by Burtannia** [comment]
@snoyberg I'm currently setting up the `.cabal` and `LICENSE` files for this to be its own module. If it's living in this repository should I keep your details in the maintainer section?

**Comment by snoyberg** [comment]
That seems reasonable, though you should definitely set yourself as author. I'd also be OK with you as maintainer if you're planning on responding to PRs and issues going forward.

**Comment by Burtannia** [comment]
@snoyberg I'm not sure how much time I will have to develop this library further but I'm certainly willing to respond to issues and pull requests that are created. Is there a way to get GitHub to notify me when there's a new issue relating to this library specifically rather than all issues for the repository?

**Comment by snoyberg** [comment]
Not that I'm aware of.

Note that there are currently conflicts in this PR that need to be resolved.

**Comment by Burtannia** [comment]
@snoyberg The conflicts should be resolved after I remove the changes I made to the `yesod-form` version now that this is going to be its own library. Do I need to manually put the library on hackage or do libraries get automatically uploaded from this repo?

**Comment by snoyberg** [comment]
You should manually upload to Hackage after this gets merged. And please add my account, `MichaelSnoyman`, as an allowed uploader as well using the Hackage web interface.

**Comment by snoyberg** [comment]
@Burtannia I've given you commit access to this repo. This PR looks fine to me. When ready, please merge.

**Comment by Burtannia** [comment]
I think that's everything sorted now. I believe that the failing CI was a connection timeout or something similar.

**Comment by Burtannia** [comment]
@snoyberg I'm still seeing `Only those with write access to this repository can merge pull requests.`. Maybe it just takes a little time to update access? Also is there any preference between merging all commits / squashing and merging?

**Comment by snoyberg** [comment]
No preference on merging vs squashing. Did you receive an invite link in your email?

**Comment by Burtannia** [comment]
@snoyberg All sorted now, didn't realise there was an email invitation involved. Thanks for all the help!

**Comment by amitaibu** [comment]
@Burtannia thanks for this :+1: . Any chance for having an example file similar to the one in -https://github.com/yesodweb/yesod/blob/b5fb6caca0a79094f2a8f6064bfb5b3009700e86/yesod-form/hello-forms.hs ?

So it's easier to see how to wire the new field type.

**Pull request merged**
