### PR TITLE
Always apply jsAttributes to scritps in body

### PR DESCRIPTION
**Pull request by dten**
Before submitting your PR, check that you've:

- [x] Bumped the version number

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

Discussion over here https://github.com/yesodweb/yesod/issues/1835 but basically right now these jsAttributes only apply if you have cached the script to a location and are unusable otherwise.

### CODE REVIEW

**Review by jezen — APPROVED** [review]
This looks good. Thank you!

**Comment by dten** [comment]
Thanks, do you have any idea where this might get released?

**Comment by jezen** [comment]
I don't as I'm not a maintainer on Hackage, but we could ask, _e.g._, @psibi or @parsonsmatt.

**Comment by parsonsmatt** [comment]
I've uploaded [`yesod-core-1.6.26.0`](https://hackage.haskell.org/package/yesod-core-1.6.26.0), thank you!

**Comment by dten** [comment]
Thanks very much

**Pull request merged**
