### PR TITLE
Yesod init new args name and database

### LINKED ISSUE #974: Supplement "yesod init" interactive mode with non-interactive mode
I was wondering if it might be possible in the future that "yesod init" could accept the app name and database backend as inline arguments to the yesod init command itself. This would allow me to wrap yesod init inside a fish shell function that also did other repetitive things (like initializing a git repo, or generating a dash-haskell docset), by just passing the arguments to the fish function, which in turn would then be able to pass them to yesod init.  It would be nice to retain the --bare flag for both modes of yesod init too.

Thank you for any consideration of this enhancement request :)

### PR DESCRIPTION
**Pull request by triplepointfive**
This resolves #974

### CODE REVIEW

**Comment by snoyberg** [comment]
Note that #987 is intended for the same thing. I'm looking at both of these, I'll have to figure out which one to merge.

**Comment by triplepointfive** [comment]
Fair enough

**Comment by snoyberg** [comment]
Since the Travis tests are failing here, I've focused my review on #987 instead.

**Comment by triplepointfive** [comment]
Build is fixed

**Comment by snoyberg** [comment]
Thank you!

**Pull request merged**
