### PR TITLE
update testing instructions according to #1018

### PR DESCRIPTION
**Pull request by danse**

### CODE REVIEW

**Comment by danse** [comment]
I was having errors running `stack exec -- yesod test` after scaffolding a new app, then i found on #1018 that other users had the same problems and that the general suggestion is to use `stack test` directly. So i thought to update the text

**Comment by snoyberg** [comment]
Please send this PR to the postgres branch of the yesod-scaffold repo: https://github.com/yesodweb/yesod-scaffold

**Comment by danse** [comment]
[Here](https://github.com/yesodweb/yesod-scaffold/pull/115) is that pull request. I will try to do similar pull requests on the other relevant branches. In general i try to avoid using branches in order to logically group code, it makes reuse and maintenance harder in my opinion. Branches just were not designed for that

**Comment by danse** [comment]
For example, in this case i need to do a full text search for "yesod test". That was easier here than in the different branches

**Comment by danse** [comment]
Luckily i can use this pull request as an index of branches to look in :P

**Comment by danse** [comment]
Pull requests from 115 to 120 on `yesod-scaffold` correspond to this

**Pull request closed without merging**
